repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.10.14

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ['--profile', 'black']


  - repo: local
    hooks:
      - id: jira-ticket-hook
        name: jira-ticket-hook
        entry: scripts/add_jira_ticket.sh
        language: script
        stages: [prepare-commit-msg]
